services:
  # =========================
  # Server - FastAPI
  # =========================
  server:
    build: ./server
    deploy:
      replicas: 5
    volumes:
      - ./server:/app
    networks:
      - app-network
    restart: always
    depends_on:
      - postgres
      - redis
      - opentelemetry-collector
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`server.localhost`)"
      - "traefik.http.routers.server.entrypoints=web"
      - "traefik.http.services.server.loadbalancer.server.port=8000"

  # =========================
  # Traefik reverse proxy
  # src: https://doc.traefik.io/traefik/getting-started/docker
  # =========================
  traefik:
    image: traefik:v3.6.8
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
    restart: always

  # =========================
  # Postgres
  # =========================
  postgres:
    image: postgres:18-alpine3.23
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  # =========================
  # Redis
  # =========================
  redis:
    image: redis:8.6.0-alpine3.23
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped

  # =========================
  # MinIO (S3 Storage)
  # =========================
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network
    restart: unless-stopped
    labels:
      - "traefik.http.routers.minio-console.rule=Host(`minio.localhost`)"
      - "traefik.http.routers.minio-console.entrypoints=web"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"

  # =========================
  # Grafana - use template 1860
  # =========================
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  # =========================
  # Prometheus
  # =========================
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
    depends_on:
      - opentelemetry-collector
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  # =========================
  # Prometheus - Alertmanager
  # =========================
  alertmanager:
    image: prom/alertmanager:latest
    container_name: prometheus-alertmanager
    volumes:
      - ./observability/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.localhost`)"
      - "traefik.http.routers.alertmanager.entrypoints=web"
      - "traefik.http.services.alertmanager.loadbalancer.server.port=9093"

  # =========================
  # Prometheus - Node Exporter
  # =========================
  node-exporter:
    image: prom/node-exporter:latest
    container_name: prometheus-node-exporter
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(sys|proc|dev|host|etc)($|/)"
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - app-network

  # =========================
  # Prometheus - Postgres Exporter
  # =========================
  postgres-exporter:
    image: bitnami/postgres-exporter:latest
    container_name: prometheus-postgres-exporter
    environment:
      DATA_SOURCE_NAME: postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE}?sslmode=disable
    ports:
      - "9186:9186"
    networks:
      - app-network
    depends_on:
      - postgres

  # =========================
  # Prometheus - Redis Exporter
  # =========================
  redis-exporter:
    image: bitnami/redis-exporter:latest
    container_name: prometheus-redis-exporter
    environment:
      - REDIS_ADDR=redis:${REDIS_PORT}
      - REDIS_PASSWORD=
    ports:
      - "9120:9121"
    networks:
      - app-network
    depends_on:
      - redis

  # =========================
  # Loki
  # =========================
  loki:
    image: grafana/loki:2.9.1
    container_name: grafana-loki
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./observability/loki/loki-config.yml:/etc/loki/local-config.yml
    ports:
      - "3100:3100"
    networks:
      - app-network
    depends_on:
      - minio

  # =========================
  # Tempo
  # =========================
  tempo:
    container_name: grafana-tempo
    image: grafana/tempo:2.10.0
    command: [-config.file=/etc/tempo/config.yml]
    environment:
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
    volumes:
      - ./observability/tempo/tempo-config.yml:/etc/tempo/config.yml
    ports:
      - "3200:3200"
    networks:
      - app-network
    depends_on:
      - minio

  # =========================
  # OpenTelemetry Collector
  # =========================
  opentelemetry-collector:
    container_name: opentelemetry-collector
    image: otel/opentelemetry-collector
    command: --config=/etc/otelcol/config.yml
    volumes:
      - ./observability/opentelemetry/otel-collector-config.yml:/etc/otelcol/config.yml
    ports:
      - 8889:8889 # Prometheus exporter metrics
    networks:
      - app-network

  # # =========================
  # # k6 - Load Testing
  # # =========================
  # k6:
  #   image: grafana/k6:latest
  #   entrypoint: ["tail", "-f", "/dev/null"]
  #   volumes:
  #     - ./scripts:/scripts
  #   networks:
  #     - app-network
  #   depends_on:
  #     - server

# =========================
# Volumes
# =========================
volumes:
  postgres_data:
  minio_data:

# =========================
# Networks
# =========================
networks:
  app-network:
    name: app-network
    driver: bridge
