scrape_configs:
  - job_name: "app"
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets:
          - "observability-app-1:8000"
          - "observability-app-1:8000"
          - "observability-app-2:8000"
          - "observability-app-3:8000"
          - "observability-app-4:8000"
          - "observability-app-5:8000"
