auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
  aws:
    s3: http://minio:9000
    bucketnames: loki
    access_key_id: ${MINIO_USER}
    secret_access_key: ${MINIO_PASSWORD}
    s3forcepathstyle: true
    insecure: true

compactor:
  working_directory: /loki/compactor
  shared_store: s3

limits_config:
  retention_period: 168h
