groups:
  - name: server-alerts
    rules:
      - alert: HighErrorRate
        expr: rate(app_requests_total{http_status=~"5.."}[1m]) > 1
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "More than 1 error per second"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(app_request_duration_seconds_bucket[5m])) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "P95 latency > 1 second"

      - alert: PostgresDown
        expr: up{job="postgres"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Postgres is down"
